services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/home/maxkaizo/DE_Zoomcamp/module_1/docker_sql/ny_taxi_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "/home/maxkaizo/DE_Zoomcamp/module_1/docker_sql/pg_data:/var/lib/pgadmin"
    ports:
      - "8090:80"
    # command: ["sh", "-c", "chown -R 5050:5050 /var/lib/pgadmin && /entrypoint.sh"]